wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1671671305.670436
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.7.15
      5: 0.13.5
      8:
      - 5
amp:
  desc: null
  value: true
arch_learning_rate:
  desc: null
  value: 0.0003
arch_weight_decay:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 1
beta1:
  desc: null
  value: 0.5
bilinear:
  desc: null
  value: false
channels:
  desc: null
  value: 1
checkpoints_dir:
  desc: null
  value: ./checkpoints
classes:
  desc: null
  value: 2
continue_train:
  desc: null
  value: false
cuda:
  desc: null
  value: true
cuda_index:
  desc: null
  value: 0
dataroot:
  desc: null
  value: ../data/JSRT
dataset_mode:
  desc: null
  value: aligned
direction:
  desc: null
  value: BtoA
display_freq:
  desc: null
  value: 100
download:
  desc: null
  value: 'False'
epoch:
  desc: null
  value: latest
epoch_count:
  desc: null
  value: 1
epochs:
  desc: null
  value: 50
gan_mode:
  desc: null
  value: vanilla
generator_iters:
  desc: null
  value: 10000
gpu_ids:
  desc: null
  value:
  - 0
init_gain:
  desc: null
  value: 0.02
init_type:
  desc: null
  value: normal
input_nc:
  desc: null
  value: 1
isTrain:
  desc: null
  value: true
is_train:
  desc: null
  value: 'True'
lambda_L1:
  desc: null
  value: 100.0
load_D:
  desc: null
  value: 'False'
load_G:
  desc: null
  value: 'False'
load_iter:
  desc: null
  value: 0
load_size:
  desc: null
  value: 286
lr:
  desc: null
  value: 0.0002
lr_decay_iters:
  desc: null
  value: 50
lr_policy:
  desc: null
  value: linear
model:
  desc: null
  value: pix2pix
model_1:
  desc: null
  value: DCGAN
momentum:
  desc: null
  value: 0.9
n_epochs:
  desc: null
  value: 10
n_epochs_decay:
  desc: null
  value: 20
n_layers_D:
  desc: null
  value: 3
name:
  desc: null
  value: experiment_name
ndf:
  desc: null
  value: 64
netD:
  desc: null
  value: basic
netG:
  desc: null
  value: unet_256
ngf:
  desc: null
  value: 64
no_dropout:
  desc: null
  value: false
norm:
  desc: null
  value: batch
output_nc:
  desc: null
  value: 1
phase:
  desc: null
  value: train
pool_size:
  desc: null
  value: 0
print_freq:
  desc: null
  value: 100
save_by_iter:
  desc: null
  value: false
save_epoch_freq:
  desc: null
  value: 1
save_latest_freq:
  desc: null
  value: 5000
scale:
  desc: null
  value: 0.5
suffix:
  desc: null
  value: ''
test_percent:
  desc: null
  value: 30.0
unet_learning_rate:
  desc: null
  value: 1.0e-05
val_percent:
  desc: null
  value: 10.0
verbose:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.0003
