python running_files/test.py \
    --model pix2pix  \
    --is_train True \
    --cuda True \
    --gpu_ids 1 \
    --cuda_index 1 \
    --dataroot ../data/ISIC2018 \
    --amp \
    --loss_lambda 1.0 \
    --n_epochs 5000 \
    --unet_epoch 20 \
    --lr 2e-7 \
    --arch_lr 1e-7 \
    --display_freq 10 \
    --classes 1 \
    --output_nc 3 \
    --input_nc 1 \
    --batch_size 2 \
    --seg_model unet \
    --model_dir /home/li/workspace/semantic_segmentation/checkpoint_skin_more/end2end-ISIC-40-unet-1.0-20230516-163031/unet_final.pkl